### ISSUE TITLE
Part 2 Paper

### ISSUE THREAD

**Issue by andrewcz** [cvxgrp/cvxstatarb#33]
Hi @kasperjo , in the paper it was mentioned that there is a part 2 being worked on.
Just wondering on the eta for this.

**Comment by kasperjo** [comment]
Hi Andrew! It's coming together, and we'll hopefully be able to post it in the coming month!

**Comment by andrewcz** [comment]
Thank you @kasperjo !! i have to be honest...I'm super excited!! 
have a great weekend!!
